### ISSUE TITLE
xcvrd NameError: global name 'select' is not defined

### ISSUE THREAD

**Issue by pavel-shirshov** [Azure/sonic-platform-daemons#18]
Current master gives me following error in syslog
```
Oct  4 00:09:52.935763 str-s6100-acs-1 INFO pmon#xcvrd: Start main loop
Oct  4 00:09:52.936035 str-s6100-acs-1 INFO pmon#supervisord: xcvrd Traceback (most recent call last):
Oct  4 00:09:52.937167 str-s6100-acs-1 INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 449, in <module>
Oct  4 00:09:52.937167 str-s6100-acs-1 INFO pmon#supervisord: xcvrd     main()
Oct  4 00:09:52.937167 str-s6100-acs-1 INFO pmon#supervisord: xcvrd   File "/usr/bin/xcvrd", line 415, in main
Oct  4 00:09:52.937167 str-s6100-acs-1 INFO pmon#supervisord: xcvrd     status, port_dict = platform_sfputil.get_transceiver_change_event()
Oct  4 00:09:52.937167 str-s6100-acs-1 INFO pmon#supervisord: xcvrd   File "/usr/share/sonic/platform/plugins/sfputil.py", line 454, in get_transceiver_change_event
Oct  4 00:09:52.937327 str-s6100-acs-1 INFO pmon#supervisord: xcvrd     epoll = select.epoll()
Oct  4 00:09:52.937327 str-s6100-acs-1 INFO pmon#supervisord: xcvrd NameError: global name 'select' is not defined
```

**Comment by Anandaraj-Maharajan** [comment]
@paavaanan from Dell is looking into it. Please assign it to him.
